### ISSUE TITLE
Rajout d'une action SMTP si echec

### ISSUE THREAD

**Issue by ghost** [Blount/LBCAlerte#16]
Je propose de modifier le code source en cas d'echec SMTP pour ne pas perdre d'alerte ainsi qu'un lien pour l'affichage mobile

Je laisse bien sur au createur d'approuver ou non, ou meme d'ameliorer !

**Comment by Blount** [comment]
Je ne pense pas répondre à la demande car je ne vois pas trop d'intérêt.
Je clos le ticket.
