### ISSUE TITLE
Comportement bizarre

### ISSUE THREAD

**Issue by lbmh** [Blount/LBCAlerte#20]
![capture d ecran 2015-02-14 12 07 00](https://cloud.githubusercontent.com/assets/6378309/6199402/1466be1c-b442-11e4-8141-220b15f8ddcc.png)

J'ai défini une recherche lbc assez simple :

http://www.leboncoin.fr/annonces/offres/ile_de_france/occasions/?f=a&th=1&q=loro+piana&it=1

qui, de façon intermittente, donne l'impression d'avoir pété un câble
ce jour elle renvoie toutes les annonces -MAISON- en Bourgogne qui ont "ancien" dans leur titre
voir fichier joint

Je ne sais pas si le souci  vient du LBC Alert, ou est un bug (ou une contre-mesure....)
émanant du Boncoin ?

Aurais tu une idée  ?

**Comment by Blount** [comment]
Aucune idée.
Tu as toujours le souci ?

**Comment by lbmh** [comment]
Oui, par intermittence. Pas très grave, ‎mais donne une impression bizare.                                                                                                                                                                                                                                                                                                                                        Laurent@Breyton.fr+33672146018                                                                                                                                                                                                                De: BlountEnvoyé: mercredi 11 mars 2015 10:38À: Blount/LBCAlerteRépondre à: Blount/LBCAlerteCc: lbmhObjet: Re: [LBCAlerte] Comportement bizarre (#20)Aucune idée.
Tu as toujours le souci ?

—Reply to this email directly or view it on GitHub.

**Comment by lbmh** [comment]
Un exemple -de l'instant- ci-dessous : la recherche d'enveloppes
pré-affranchies dans Articles de bureau dans toute la France retourne
des Audis A4 TDI dans les Voitures de Picardie....

C'est juste une fois tous les 3-4 jours....


On Wed, Mar 11, 2015, at 10:49, Laurent BREYTON wrote:
> Oui, par intermittence. Pas très grave, ‎mais donne une
> impression bizare.
>
> Laurent@Breyton.fr +33672146018 *De: *Blount *Envoyé: *mercredi 11
> mars 2015 10:38 *À: *Blount/LBCAlerte *Répondre à: *Blount/LBCAlerte
> *Cc: *lbmh *Objet: *Re: [LBCAlerte] Comportement bizarre (#20)
>
>
> Aucune idée.
>
Tu as toujours le souci ?

> — Reply to this email directly or view it on GitHub[1].

>
>

LB GSM +33672146018


----- Original message ----- From: "alerte_boncoin@fea.st"
<alerte_boncoin@fea.st> To: alerte_boncoin@fea.st Subject: Alert
LeBonCoin : Enveloppes pré-affranchies Date: Wed, 11 Mar 2015
11:01:04 +0100

Alerte générée le 11/03/2015 11:01


Lien de recherche:
http://www.leboncoin.fr/fournitures_de_bureau/offres/ile_de_france/occasions/?f=a&th=1&q=enveloppes+*affranch*&it=1


Liste des nouvelles annonces :



*Publié le 2015/03/10 22:36* *Nom* : A4 2.7l V6 TDi 190 Ambition Luxe
Multitronic[2] *Prix* : 15 500 € *Département* : Oise *Ville* : Noyon[3]
Annonce de particulier.



*Publié le 2015/03/10 15:46* *Nom* : Audi A4 IV AVANT ambition luxe
SLINE tdi 143 LED[4] *Prix* : 16 800 € *Département* : Somme *Ville* :
Amiens[5] Annonce de particulier.



*Publié le 2015/03/10 13:10* *Nom* : Audi A4 Tdi 140 ch S-line[6] *Prix*
: 10 900 € *Département* : Somme *Ville* : Péronne[7] Annonce de
particulier.



*Publié le 2015/03/09 21:52* *Nom* : Audi A4 cabriolet - 2.0 tdi - Full
option[8] *Prix* : 19 000 € *Département* : Oise Annonce de particulier.



*Publié le 2015/03/09 14:22* *Nom* : Audi A4 Avant 3.0 TDI 204CH MULTI 8
AMBITION LUXE[9] *Prix* : 29 900 € *Département* : Aisne *Ville* :
Laon[10] Annonce de professionnel



*Publié le 2015/03/09 11:52* *Nom* : Audi A4 S LINE 3.0 TDI 204[11]
*Prix* : 28 990 € *Département* : Oise *Ville* : Beauvais[12] Annonce de
professionnel



*Publié le 2015/03/09 11:23* *Nom* : Audi A4 3.0 TDI 204CH[13] *Prix* :
36 990 € *Département* : Oise *Ville* : Beauvais[14] Annonce de
professionnel



*Publié le 2015/03/09 09:13* *Nom* : Audi A4 3.0 TDI 245 CH[15] *Prix* :
31 990 € *Département* : Oise *Ville* : Beauvais[16] Annonce de
professionnel



*Publié le 2015/03/08 17:05* *Nom* : Audi A4 Avant 2.0 TDI 143 S Line
5[17] *Prix* : 25 490 € *Département* : Oise *Ville* : Compiègne[18]
Annonce de professionnel



*Publié le 2015/03/08 14:43* *Nom* : Audi a4 avant 2.0 tdi 143cv
ambition xenon gps[19] *Prix* : 16 680 € *Département* : Oise *Ville* :
Candor[20] Annonce de particulier.



*Publié le 2015/03/07 23:16* *Nom* : Audi A4 avant tdi 143[21] *Prix* :
15 490 € *Département* : Oise *Ville* : Compiègne[22] Annonce de
particulier.



*Publié le 2015/03/07 16:24* *Nom* : AUDI A4 AVANT 2,0L TDI 143 année
07/2011[23] *Prix* : 18 290 € *Département* : Oise *Ville* :
Margny-lès-Compiègne[24] Annonce de particulier.



*Publié le 2015/03/07 08:31* *Nom* : Audi a4 b8 2.0 tdi 143cv[25] *Prix*
: 11 700 € *Département* : Oise *Ville* : Compiègne[26] Annonce de
particulier.



*Publié le 2015/03/06 15:13* *Nom* : Audi A4 CAB 2.0 TDI 140 DPF S
LINE[27] *Prix* : 16 980 € *Département* : Somme *Ville* : Salouël[28]
Annonce de professionnel



*Publié le 2015/03/06 13:25* *Nom* : A4 Allroad 3.0 TDI Ambition Luxe S
Tronic[29] *Prix* : 26 990 € *Département* : Somme *Ville* :
Abbeville[30] Annonce de professionnel



*Publié le 2015/03/06 11:58* *Nom* : Audi A4 avant 2.0 TDI 120 ambition
luxe[31] *Prix* : 19 000 € *Département* : Oise *Ville* : Betz[32]
Annonce de particulier.



*Publié le 2015/03/06 08:23* *Nom* : Audi A4 Allroad 2.0 TDI 177
Ambiente S Tronic[33] *Prix* : 39 900 € *Département* : Somme *Ville* :
Rivery[34] Annonce de professionnel



*Publié le 2015/03/05 20:01* *Nom* : Audi a4 ambiente tdi 2l 143ch[35]
*Prix* : 12 200 € *Département* : Aisne *Ville* : Frières-Faillouël[36]
Annonce de particulier.



*Publié le 2015/03/05 12:13* *Nom* : Audi A4 Avant 2.0 TDI QUATTRO[37]
*Prix* : 39 990 € *Département* : Oise *Ville* : Beauvais[38] Annonce de
professionnel



*Publié le 2015/03/05 11:47* *Nom* : A4 2.7 tdi[39] *Prix* : 15 300 €
*Département* : Oise *Ville* : Verneuil-en-Halatte[40] Annonce de
particulier.



*Publié le 2015/03/05 10:58* *Nom* : Audi A4 3.0 TDI QUATTRO S-LINE[41]
*Prix* : 26 990 € *Département* : Oise *Ville* : Beauvais[42] Annonce de
professionnel



*Publié le 2015/03/05 08:54* *Nom* : Audi A4 2.7 TDI[43] *Prix* : 22 990
€ *Département* : Oise *Ville* : Beauvais[44] Annonce de professionnel



*Publié le 2015/03/04 17:43* *Nom* : Audi A4 2.0 TDI S-Line Navi
Xenon[45] *Prix* : 23 990 € *Département* : Aisne *Ville* :
Villequier-Aumont[46] Annonce de professionnel



*Publié le 2015/03/04 12:06* *Nom* : Audi a4 avant s line 190cv tdi[47]
*Prix* : 41 990 € *Département* : Somme Annonce de professionnel



*Publié le 2015/03/04 11:16* *Nom* : AUDI A4 Ambiente 2.0 TDI 143
Multitronic[48] *Prix* : 14 400 € *Département* : Oise Annonce de
particulier.



*Publié le 2015/03/04 10:35* *Nom* : Audi A4 Avant 2.0 TDI 150 DPF S
LINE[49] *Prix* : 30 900 € *Département* : Somme *Ville* : Albert[50]
Annonce de professionnel



*Publié le 2015/03/04 01:59* *Nom* : Audi a4 2l tdi ambition luxe 170cv
fin 2009[51] *Prix* : 16 800 € *Département* : Oise Annonce de
particulier.



*Publié le 2015/03/03 21:28* *Nom* : Audi A4 2.0L TDI AMBIENTE 120CH[52]
*Prix* : 21 500 € *Département* : Oise *Ville* : Saint-Maximin[53]
Annonce de professionnel



*Publié le 2015/03/03 17:42* *Nom* : Audi a4 allroad 2.0 tdi 143[54]
*Prix* : 27 990 € *Département* : Aisne *Ville* : Saint-Quentin[55]
Annonce de professionnel



*Publié le 2015/03/03 16:09* *Nom* : Audi a4 sline 2.0 tdi[56] *Prix* :
14 900 € *Département* : Oise *Ville* : Senlis[57] Annonce de
particulier.



*Publié le 2015/03/03 15:04* *Nom* : A4 2.0 TDI 143ch Ambiente 2010[58]
*Prix* : 14 500 € *Département* : Oise *Ville* : Catenoy[59] Annonce de
particulier.



*Publié le 2015/03/03 15:02* *Nom* : Audi a4 break 3.0 v6 tdi[60] *Prix*
: 7 000 € *Département* : Somme *Ville* : Drucat[61] Annonce de
particulier.



*Publié le 2015/03/03 09:55* *Nom* : Audi A4 Avant 2.0 TDI S LINE[62]
*Prix* : 29 990 € *Département* : Oise *Ville* : Beauvais[63] Annonce de
professionnel



*Publié le 2015/03/03 08:18* *Nom* : Audi A4 Avant S LINE 2.0 TDI
QUATTRO[64] *Prix* : 30 990 € *Département* : Oise *Ville* :
Beauvais[65] Annonce de professionnel





Links:

   1. https://github.com/Blount/LBCAlerte/issues/20#issuecomment-78231343
   2. http://www.leboncoin.fr/voitures/778939392.htm?ca=12_s
   3. http://maps.google.fr/?z=9&q=Oise%20Noyon
   4. http://www.leboncoin.fr/voitures/778765992.htm?ca=12_s
   5. http://maps.google.fr/?z=9&q=Somme%20Amiens
   6. http://www.leboncoin.fr/voitures/778699918.htm?ca=12_s
   7. http://maps.google.fr/?z=9&q=Somme%20P%C3%A9ronne
   8. http://www.leboncoin.fr/voitures/778526690.htm?ca=12_s
   9. http://www.leboncoin.fr/voitures/778547847.htm?ca=12_s
  10. http://maps.google.fr/?z=9&q=Aisne%20Laon
  11. http://www.leboncoin.fr/voitures/778370959.htm?ca=12_s
  12. http://maps.google.fr/?z=9&q=Oise%20Beauvais
  13. http://www.leboncoin.fr/voitures/778371029.htm?ca=12_s
  14. http://maps.google.fr/?z=9&q=Oise%20Beauvais
  15. http://www.leboncoin.fr/voitures/778371016.htm?ca=12_s
  16. http://maps.google.fr/?z=9&q=Oise%20Beauvais
  17. http://www.leboncoin.fr/voitures/778031183.htm?ca=12_s
  18. http://maps.google.fr/?z=9&q=Oise%20Compi%C3%A8gne
  19. http://www.leboncoin.fr/voitures/777863059.htm?ca=12_s
  20. http://maps.google.fr/?z=9&q=Oise%20Candor
  21. http://www.leboncoin.fr/voitures/777680538.htm?ca=12_s
  22. http://maps.google.fr/?z=9&q=Oise%20Compi%C3%A8gne
  23. http://www.leboncoin.fr/voitures/658820551.htm?ca=12_s
  24. http://maps.google.fr/?z=9&q=Oise%20Margny-l%C3%A8s-Compi%C3%A8gne
  25. http://www.leboncoin.fr/voitures/777330460.htm?ca=12_s
  26. http://maps.google.fr/?z=9&q=Oise%20Compi%C3%A8gne
  27. http://www.leboncoin.fr/voitures/717088970.htm?ca=12_s
  28. http://maps.google.fr/?z=9&q=Somme%20Salou%C3%ABl
  29. http://www.leboncoin.fr/voitures/756999606.htm?ca=12_s
  30. http://maps.google.fr/?z=9&q=Somme%20Abbeville
  31. http://www.leboncoin.fr/voitures/777033127.htm?ca=12_s
  32. http://maps.google.fr/?z=9&q=Oise%20Betz
  33. http://www.leboncoin.fr/voitures/776960446.htm?ca=12_s
  34. http://maps.google.fr/?z=9&q=Somme%20Rivery
  35. http://www.leboncoin.fr/voitures/776843720.htm?ca=12_s
  36. http://maps.google.fr/?z=9&q=Aisne%20Fri%C3%A8res-Faillou%C3%ABl
  37. http://www.leboncoin.fr/voitures/776855941.htm?ca=12_s
  38. http://maps.google.fr/?z=9&q=Oise%20Beauvais
  39. http://www.leboncoin.fr/voitures/771535782.htm?ca=12_s
  40. http://maps.google.fr/?z=9&q=Oise%20Verneuil-en-Halatte
  41. http://www.leboncoin.fr/voitures/776640051.htm?ca=12_s
  42. http://maps.google.fr/?z=9&q=Oise%20Beauvais
  43. http://www.leboncoin.fr/voitures/776640009.htm?ca=12_s
  44. http://maps.google.fr/?z=9&q=Oise%20Beauvais
  45. http://www.leboncoin.fr/voitures/741220979.htm?ca=12_s
  46. http://maps.google.fr/?z=9&q=Aisne%20Villequier-Aumont
  47. http://www.leboncoin.fr/voitures/767551469.htm?ca=12_s
  48. http://www.leboncoin.fr/voitures/776224678.htm?ca=12_s
  49. http://www.leboncoin.fr/voitures/527486832.htm?ca=12_s
  50. http://maps.google.fr/?z=9&q=Somme%20Albert
  51. http://www.leboncoin.fr/voitures/776137990.htm?ca=12_s
  52. http://www.leboncoin.fr/voitures/776127360.htm?ca=12_s
  53. http://maps.google.fr/?z=9&q=Oise%20Saint-Maximin
  54. http://www.leboncoin.fr/voitures/775981961.htm?ca=12_s
  55. http://maps.google.fr/?z=9&q=Aisne%20Saint-Quentin
  56. http://www.leboncoin.fr/voitures/775942283.htm?ca=12_s
  57. http://maps.google.fr/?z=9&q=Oise%20Senlis
  58. http://www.leboncoin.fr/voitures/775909953.htm?ca=12_s
  59. http://maps.google.fr/?z=9&q=Oise%20Catenoy
  60. http://www.leboncoin.fr/voitures/726033036.htm?ca=12_s
  61. http://maps.google.fr/?z=9&q=Somme%20Drucat
  62. http://www.leboncoin.fr/voitures/776008755.htm?ca=12_s
  63. http://maps.google.fr/?z=9&q=Oise%20Beauvais
  64. http://www.leboncoin.fr/voitures/775860767.htm?ca=12_s
  65. http://maps.google.fr/?z=9&q=Oise%20Beauvais

**Comment by Blount** [comment]
C'est dingue ça.
Tu pourrait m'envoyer ton fichier CSV par mail ? blount@ilatumi.org

**Comment by lbmh** [comment]
En attache, admin.csv.

Mon intuition c'est que le souci est chez leboncoin....

On Wed, Mar 11, 2015, at 12:14, Blount wrote:
> C'est dingue ça.
>
Tu pourrait m'envoyer ton fichier CSV par mail ? blount@ilatumi.org

> —
>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/Blount/LBCAlerte/issues/20#issuecomment-78244634

**Comment by lbmh** [comment]
Passé en 2.5, sans difficultés, en revanche le titre des annonces rapportées disparait comme précédemment.

Par ailleurs l'upgrade en 2.6.2 bloque ...

**Comment by lbmh** [comment]
De retour de vacances et bien décidé à
faire marcher LBC, je viens de faire une install fraiche de
la 2.6.2 où j'ai importé mes règles de la 2.5 :+1: 
impossible de faire partir un e-mail de test.

j'ai vérifié et revérifié et encore vérifié mes paramètres SMTP,
et j'ai tenté sans succès sans sécurité, en TSL et en SSL, rien n'y fait 
l'e-mail de test part pas avec le message 

Erreur de l'envoi du mail : Erreur SMTP : échec de l'authentification.

Merci d'avance de ton aide.

**Comment by Blount** [comment]
Bon, aucun avancement dans ce sujet, je le clos donc.
