### ISSUE TITLE
Le filtrage des catégories pose problème

### ISSUE THREAD

**Issue by tmarly** [Blount/LBCAlerte#22]
Bonjour,

J'ai remarqué que lorsque dans les paramètres avancés (pour les alertes mail), on coche une catégorie, on risque de ne recevoir aucune alerte.

Le pb se situe dans le [parser ligne 128](https://github.com/Blount/LBCAlerte/blob/master/lib/Lbc/Parser.php#L128):
```php
if ($filters["categories"] && !in_array($ad->getCategory(), $filters["categories"])) {
  continue;
}
```

$ad->getCategory() est souvent vide (j'ai trouvé peu d'exemples d'url LBC qui fournit un div contenant la catégorie), du coup si on a coché une catégorie, le résultat du test est true, l'annonce n'est donc pas retenue. Il faudrait remplacer par:

```php
if ($ad->getCategory() != '' && $filters["categories"] && !in_array($ad->getCategory(), $filters["categories"])) {
  continue;
}
```

++

**Comment by Blount** [comment]
Sur LBC, lorsqu'on fait une recherche sur une catégorie, alors effectivement les catégories ne sont pas affichées sur la page. Mais dans ce cas, le filtre est inutile puisque qu'on a déjà fait le filtre sur la recherche LBC.

Par contre, quand tu fais une recherche "Toutes catégories", alors les catégories sont affichées.

En fait, pour bien faire, il faudrait que je détecte dans l'URL de recherche LBC si la personne a fait sa recherche sur une catégorie. Si oui, alors il faudrait masquer le filtre par catégorie de l'alerte.

**Comment by tmarly** [comment]
Ok, je comprends effectivement.
Mais c'est un comportement à connaitre, car j'ai qq amis qui ne recevaient pas d'alertes, ils ont coché la catégorie sans penser mal faire ...
En tout cas bien pratique ce script !

**Comment by Blount** [comment]
Ok.
Je vais voir, je voulais eviter d'insérer trop de JavaScript car ça peut ajouter de la lourdeur à maintenir et une couche supplémentaire de bug possible.
Je vais y réfléchir ;)

**Comment by tmarly** [comment]
Impec le warning, merci :)
