### ISSUE TITLE
Le nom des annonces retournées n'est plus visible dans les emails

### ISSUE THREAD

**Issue by AlainMuller** [Blount/LBCAlerte#23]
Bonjour,

depuis quelques jours, je reçois des emails indiquant des offres dont le nom n'est plus renseigné.
Ce dernier contient le lien vers l'annonce sur leboncoin, il est donc difficile d'accéder rapidement à l'annonce sans cette donnée...

ci-dessous un exemple de contenu de mail reçu : 
> Alerte générée le 03/04/2015 14:20
> 
> Lien de recherche: http://www.leboncoin.fr/annonces/offres/bretagne/occasions/?f=a&sp=0&th=1&q=NF310&it=1
> 
> Liste des nouvelles annonces :
> 
> 
> Publié le 2015/03/31 11:42 
> Nom :     Prix : 140 € 
> Catégorie : Informatique 
> Département : Val-de-Marne     Ville : Thiais 
> Annonce de particulier. 

Avec la photo c'est plus parlant : 
![image](https://cloud.githubusercontent.com/assets/2368948/6982211/d7157c4a-da0e-11e4-8798-933e926889e3.png)

Pour infos, voici code HTML (espaces compris) du titre de l'annonce sur la page leboncoin (cf. lien ci-dessus) : 
```html
<h2 class="title">
                                    Netbook samsung np-nf310 shark (nf310)+sacoche
                                 </h2>
```

Je suis une quiche en Php mais le /Lbc/Parser semble bien échapper les espaces : 
```php
} elseif ($class == "title") {
                        $ad->setTitle(trim($node->nodeValue));
                    } 
```

Serai-je le seul à avoir ce problème?

**Comment by Blount** [comment]
C'est déjà corrigé dans la dernière version.
On en parle ici :
http://alerte.ilatumi.org/forum/viewtopic.php?id=385

**Comment by AlainMuller** [comment]
Au temps pour moi, suis-je bête je n'ai même pas cherché à regarder s'il existait une version plus récente!
Merci pour la réactivité et pour le boulot! :smile:

**Comment by Blount** [comment]
De rien.
Pensez aussi à regarder sur le forum. Dans des cas comme ça, c'est le premier endroit où ça bouge ;)

**Comment by AlainMuller** [comment]
Oui merci (par contre, je ne sais pas si c'est moi mais impossible de m'inscrire sur le forum, j'ai le message d'erreur suivant) : 
> L'adresse électronique saisie est bannie de ces forums. Veuillez en choisir une autre.

Quoi qu'il en soit, je penserai à surveiller le forum la prochaine fois.
