### ISSUE TITLE
Support NMA et Pushover

### ISSUE THREAD

**Issue by silopolis** [Blount/LBCAlerte#25]
Le support des notifications push avec NotityMyAndroid et/ou Pushover serait bien venu en plus de Pushbullet :-)

**Comment by Blount** [comment]
Je vais voir à ajouter ces deux systèmes.

**Comment by Blount** [comment]
C'est fait : a454bed050a5133341378d63f19a9c907d790a49 et 449f4db2c3d35711fee6833c0bf0b77beb72ed97

**Comment by silopolis** [comment]
Royal  !

Merci

2015-11-03 21:35 GMT+01:00 Blount <notifications@github.com>:

> C'est fait : a454bed
> <https://github.com/Blount/LBCAlerte/commit/a454bed050a5133341378d63f19a9c907d790a49>
> et 449f4db
> <https://github.com/Blount/LBCAlerte/commit/449f4db2c3d35711fee6833c0bf0b77beb72ed97>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Blount/LBCAlerte/issues/25#issuecomment-153478991>.
>



-- 
--
Jérémie Tarot
http://about.me/silopolis
