### ISSUE TITLE
LBC V2.6.2 ecrasement fichier profil .csv

### ISSUE THREAD

**Issue by pelo26** [Blount/LBCAlerte#26]
Bonjour.
Je vient de metre a jour en versin 2.6.2.
et des que je veut ajouter une nouvelle recherche mon fichier csv est ecrase ( 0 octets).
si vous avez besoins d'autre infos pour aider un peu plus, demandez mois.

**Comment by Blount** [comment]
Bonjour,
Pouvez-vous mettre à jour vers la version 3.3 et me faire un retour si le problème persiste ?

**Comment by Blount** [comment]
Je clos car pas de retour.
