### ISSUE TITLE
Pas de possibilité d'envoi par commande sendmail

### ISSUE THREAD

**Issue by fastm3** [Blount/LBCAlerte#28]
Appli installée operationnelle avec reception alerte sms free.

Je desire recevoir les emails et de preference avec la fonctions sendmail de mon serveur.
Je ne remplis donc pas les champs serveur smtp , port... et effectue un test par l'interface d'administration sur la page config email. Tous les champs vides, le test est ok et je recois bien l'email de test. L'email est bien envoyé avec la commande sendmail, je le vois passer dans les logs emails du serveur.
Par contre, a l'execution du cron, je recois bien les alertes sms free mais pas l'email. Les logs indiquent: "WARN Échec de la connexion SMTP. "
Le message interpelle puisqu'il ne devrait pas y avoir de connexion directe smtp. En fait , on devrait avoir le meme comportement que dans la foncton test smtp.
Bref , je ne peux pas envoyer par la commande sendmail les alertes. Dommage car ca a certain avantages et permet une install plus "plug and play".

A noter que si je remplis un serveur smtp, ca fonctionne bien. Je pinaille donc...

**Comment by Blount** [comment]
Tu peux regarder dans ton fichier config.ini si tu trouves une section [mailer]
Si c'est la cas, supprime là et redis moi si c'est bon.

**Comment by fastm3** [comment]
Bingo !
La section existait.
En la supprimant, ca fonctionne.
Merci.

**Comment by Blount** [comment]
Ok, je laisse ouvert et j'ai marqué comme Bug pour me faire penser à corriger ce problème.
Merci du retour.
