### ISSUE TITLE
Sélection d'une adresse e-mail par défaut

### ISSUE THREAD

**Issue by sbraz** [Blount/LBCAlerte#33]
Bonjour,
Ça serait super de pouvoir associer une adresse e-mail par défaut pour chaque utilisateur pour éviter d'avoir à la taper à chaque fois.

**Comment by Blount** [comment]
Tu as raison, j'y ai déjà réfléchi, mais je n'ai pas encore eu le temps de mettre en place.

**Comment by Blount** [comment]
Bonjour,
C'est maintenant possible dans la version 3.3.
(faire un backup avant mise à jour, elle est toute fraîche ^^)
