### ISSUE TITLE
Pb avec NotifyMyAndroid

### ISSUE THREAD

**Issue by renard007** [Blount/LBCAlerte#36]
Slt, J'ai un compte premium Notify My Android, j'ai bien rentré la clé. Mais le message test ne fonctionne pas et aucune synchro.
Une idée?
Merci d'avance

**Comment by Blount** [comment]
Bonjour,
Je sais que cela fait un moment que vous avez rapporté ce souci mais je viens de faire une correction qui sera disponible dans la prochaine version.
