### ISSUE TITLE
[RSS] Retourner l'ensemble des pages de résultats dans le flux

### ISSUE THREAD

**Issue by DocteurRe** [Blount/LBCAlerte#38]
Bonjour,
Il pourrait être intéressant de retourner l'ensemble des pages de résultats de la recherche dans le flux RSS, et pas seulement la première.

Ainsi on a directement toutes les annonces existantes lorsque l'on crée une nouvelle recherche - et on peut se permettre de laisser son news aggregator fermé pendant 2 mois sans perdre une annonce.

Est-ce une demande réalisable techniquement ?

Je peux éventuellement m'y coller si vous pensez que c'est jouable.

**Comment by Blount** [comment]
Bonjour,
Le logiciel ne fait (ne fera) que récupérer les annonces de la première page. Son objectif principal est d'alerter lorsqu'une nouvelle annonce est mis en ligne, il n'a pas vocation à archiver Leboncoin ^^
