### ISSUE TITLE
Image ne s'affiche plus, lien html non fonctionnel

### ISSUE THREAD

**Issue by jzik** [Blount/LBCAlerte#39]
Bonjour,

Depuis ce matin, les images ne s'affichent plus dans les mails d'alertes, et le lien html ne fonctionne plus non plus.

A priori, il semble qu'il manche http devant les liens

<a href="//www.leboncoin.fr/bricolage/832385950.htm?ca=13_s"

"img src="//img4.leboncoin.fr/images/2d6/2d66fb81dbe310b0e29423a4268949ad428705ea.jpg" 

Patrice

**Comment by Blount** [comment]
Bonjour,
Je viens de regarder, effectivement c'est bien le http qui bloque.
Ils ont activé le https, ils ont donc changé les liens en conséquence.

Je ferai la modification ce soir.
Merci pour l'information.

**Comment by Blount** [comment]
Corrigé et mise à jour disponible.
