### ISSUE TITLE
Toujours impossible d'envoyer un e-mail de test

### ISSUE THREAD

**Issue by lbmh** [Blount/LBCAlerte#40]
Je viens de passer en 2.9.1, avec une AlerteLBC vierge,
les paramètres d'e-mail sont bons, ca bloque toujours...

Aucune idée sur ce qui se passe ?

Merci d'avance.

**Comment by Blount** [comment]
Vous pouvez regarder dans les logs serveurs (exemple: /var/log/mail.log). Il peut y avoir des infos.

**Comment by lbmh** [comment]
Malheureusement,  Il n'y a strictement rien dans les logs ni en 2.5
ni en 2.9.1


On Sun, Feb 14, 2016, at 16:36, Blount wrote:
> Vous pouvez regarder dans les logs serveurs (exemple:
> /var/log/mail.log). Il peut y avoir des infos.


> — Reply to this email directly or view it on GitHub[1].


>


Links:

  1. https://github.com/Blount/LBCAlerte/issues/40#issuecomment-183906289

**Comment by labiloute** [comment]
Lors de l'envoi de l'email de test, j'ai pour ma part une erreur sur le serveur : 

Class 'SMTP' not found in /var/www/html/cheky/lib/PHPMailer/class.phpmailer.php on line 1520,

**Comment by Blount** [comment]
Merci pour le retour.
Je viens de vérifier, en effet le test ne fonctionne pas dans le cas de l'utilisation d'un SMTP distant.
C'est du à la mise à jour de PHPMailer.
Je corrigerai ca.
