### ISSUE TITLE
Support d'autres sites type LBC

### ISSUE THREAD

**Issue by Guilhemostalier** [Blount/LBCAlerte#41]
Bonjour,

Avant tout bravo ! Je me suis installé ca pour des recherches perso ca tourne super !

Je me demandais si vous aviez au programme le support d'autres sites comme seloger logicimmo ou d'autres marketplaces type ebay ou amazon.

Merci encore

**Comment by p-antonelli** [comment]
+1

**Comment by Blount** [comment]
Sachant que les 2 sites cités permettent déjà de créer des alertes, qu'est-ce que le logiciel apporterait en plus ?

**Comment by Guilhemostalier** [comment]
- La centralisation de toutes les recherches/alertes dans un seul logiciel
- Le fait de ne pas voir ses critères de recherche et infos de contact revendues/distribuées a tous les agents immo de la région
- Le dé-doublonage d’annonces multi-sites

**Comment by Blount** [comment]
Entendu, ce sont de bon argument ^^
Par contre, le dédoublonnage apporterait beaucoup trop de contrainte au logiciel, ce ne sera certainement pas fait.

Bon, clairement, ca risque de représenter du boulot (et donc du temps) pour implémenter d'autre site, surtout en maintenance.

Vous avez d'autre site ?

**Comment by Guilhemostalier** [comment]
Voici la liste exhaustive des sites auxquels je pense.
- Leboncoin
- Seloger
- LogicImmo
- Paruvendu

MarketPlaces
- Ebay
- Amazon
- Priceminister

J'avoue que je n'en vois pas d'autre.

Mais globalement, faire abstraction du parseur LBC, pour laisser place à 
un systeme de plug-in permettrai a chacun de proposer l’intégration de 
nouveaux fournisseurs au système d'alerte.
En gros, un plugin = un fournisseur

Pour le dédoublonnage, je comprend.

Merci encore pour votre dev et vos réponses

**Comment by Blount** [comment]
Ok.
En fait, c'est déjà le cas. Je prend en charge le site russe Olx lol
Au niveau des fichiers, les parsers sont dans lib/AdService/Parser/

**Comment by Guilhemostalier** [comment]
OK, il n’y a plus qu’a en gérer d’autres dans ce cas et éventuellement d’ajouter un rubrique pour les télécharger/activer/deactiver.
En espérant que vous trouviez le temps ! :)

Bonne continuation

**Comment by Blount** [comment]
LBC vient de mettre en place leur nouveau site.
Du coup, comme la prise en charge de Seloger.com était déjà faite (Ebay en cours), je l'ai inclue dans la mise à jour.
Tu peux donc déjà tester les alertes Seloger.com, ça fonctionne pareil, tu indiques l'URL de la recherche.

**Comment by Guilhemostalier** [comment]
Je sais pas quoi répondre !! Quelle réactivité, merci beaucoup pour tout 
ca ! Je m'empresse de tester :)

**Comment by bambix** [comment]
Tout marche a merveille, je me demandais si tu pouvait pas ajouter logic immo a l'occasion, c'est vrai que ma copine s'impatiente de changer d'appartement ^^
A défaut je voulais savoir si le simple fait de dupliquer un de tes parseurs pour cibler un autre site permettait le support du site en question sur l'interface.

**Comment by arteta22000** [comment]
Bonjour,

Pourriez vous ajouter "ouestfrance-immo.com", exemple:
-> https://www.ouestfrance-immo.com/acheter/maison/rennes-35-35000/?prix=200000

Merci !

**Comment by Blount** [comment]
Bonjour,
Je vous invites à faire vos demandes d'intégration de nouveau site sur le forum : 
https://forum.cheky.net
