### ISSUE TITLE
La mise à jour auto à fonctionné, mais toujours affichage en 2.9.1

### ISSUE THREAD

**Issue by zebess** [Blount/LBCAlerte#42]
J'ai fait un update, et le ficher version est bien passé en 3.x mais l'interface est restée en 2.9.1
Une idée?
Sébastien

**Comment by Blount** [comment]
Si l'interface est en 2.9.1 c'est que c'est aussi cette version dans le fichier version.php
Si tu as 3.1 dans config.ini mais pas dans version.php, c'est qu'il y a un problème d'accès en écriture.
Le mieux est donc de remettre 2.9.1 dans config.ini et de faire en sorte que l'application puisse remplacer les fichiers.

La mise à jour auto a été amélioré dans la 3.0 justement pour contrôler les accès.
Au pire, tu peux faire une mise à jour manuelle en écrasant tous les fichiers.

**Comment by zebess** [comment]
J'ai finalement écrasé les fichiers ;-) .... et en effet, le contrôle m'a demandé de libérer le fichier version.php ... j'attendrai la prochaine version pour voir si c'est bon. Merci pour la réponse rapide.

**Comment by Blount** [comment]
Attention, le test sur version.php est juste pour savoir si la mise à jour auto peut-être fait ou non.
Si seul version.php est en écriture et pas les fichiers autour, la mise à jour ne se fera pas correctement. Il faut que TOUS les fichiers soit en accès écriture.

**Comment by zebess** [comment]
Ah d'accord, merci pour la précision! Pas le dossier APP, libs, other, rss, static,  du coup , juste les fichiers en racine à coté de version.php?

**Comment by Blount** [comment]
Non, TOUS les fichiers ^^
Il faut que l'application soit capable d'écrire sur tous les fichiers pour les mettre à jour.
Sinon, il faut passer par une mise à jour manuelle, c'est pas trop long à faire.

**Comment by zebess** [comment]
C'est fait .... plus qu'à attendre le prochain update ;-)
merci
