### ISSUE TITLE
WARN Code HTTP différent de 200 : 301 : résolu

### ISSUE THREAD

**Issue by zebess** [Blount/LBCAlerte#44]
Impossible de faire fonctionner lbc depuis hier apres midi... WARN Code HTTP différent de 200
Réinstallation complet de l'outil : idem
il semblerait que ça soit lié au https du site leboncoin.
Help

**Comment by Blount** [comment]
Peux-tu remplacer le fichier : app/mail/scripts/check.php par celui-ci : [check.txt](https://github.com/Blount/LBCAlerte/files/216568/check.txt)
(il faudra renommer le fichier en check.php)
J'ai ajouté le code HTTP retourné par la requête. Tu me diras ce qu'il y a dans tes logs après le remplacement.

**Comment by zebess** [comment]
le message a changé:
2016-04-13T13:53:39+02:00 INFO Contrôle des alertes.
2016-04-13T13:53:39+02:00 WARN Code HTTP différent de 200 : 301

**Comment by Blount** [comment]
Ok.
Tu peux regarder la configuration de ton serveur pour voir si le safe_mode de PHP est activé ou si la valeur de open_basedir est renseignée.
Je pense que ça doit venir de ça car le code 301 correspond à une redirection permanente (pour Leboncoin : HTTP > HTTPS). Mais si un de ces deux paramètres est actif, la redirection n'est pas suivis.

**Comment by zebess** [comment]
Mais si un de ces deux paramètres est actif, la redirection n'est pas suivis.: c'est à dire si le safe_mode est actif ou open_basedir?

**Comment by zebess** [comment]
"safe_mode est actif" et de "open_basedir" ne sont pas actifs sur mon synology. Et il n'y a pas eu de mise à jour depuis février sur celui-ci... apparemment je ne serais pas le seul a avoir ce souci à voir le forum.

**Comment by zebess** [comment]
J'ai également passé toute mes url en https ... mais rien de plus en résultat ... tjr cette erreur bloquante :-\

**Comment by romain1206** [comment]
pareil pour moi

**Comment by zebess** [comment]
J'ai passé mon site en https sur mon synology mais ce n'est pas mieux

**Comment by romain1206** [comment]
chez moi ça marche

2016-04-16T15:00:02+02:00 INFO 6 alertes trouvées
2016-04-16T15:00:02+02:00 INFO Contrôle de l'alerte https://www.leboncoin.fr/outillage_materiaux_2nd_oeuvre/
2016-04-16T15:00:03+02:00 INFO 8 annonces trouvées
2016-04-16T15:00:04+02:00 INFO Contrôle de l'alerte https://www.leboncoin.fr/
2016-04-16T15:00:05+02:00 INFO 35 annonces trouvées
2016-04-16T15:00:06+02:00 INFO Contrôle de l'alerte https://www.leboncoin.fr/
2016-04-16T15:00:07+02:00 INFO 35 annonces trouvées
2016-04-16T15:00:09+02:00 INFO Contrôle de l'alerte https://www.leboncoin.fr/
2016-04-16T15:00:12+02:00 INFO 25 annonces trouvées
2016-04-16T15:00:13+02:00 INFO Contrôle de l'alerte https://www.leboncoin.fr/
2016-04-16T15:00:14+02:00 INFO 35 annonces trouvées
2016-04-16T15:00:15+02:00 INFO Contrôle de l'alerte https://www.leboncoin.fr/m
2016-04-16T15:00:16+02:00 INFO 4 annonces trouvées 

remplacement de toutes les url en http par https dans le code et dans les annonces et la modif de gilles
https://alerte.ilatumi.org/forum/viewtopic.php?id=477

**Comment by zebess** [comment]
Es qu'il faut remplacer dans le fichier abstract.php tous les http en https comme par exemple cette ligne:
if ($type != self::PROXY_TYPE_http && 
en  if ($type != self::PROXY_TYPE_https && 
?
et dans ce fichier il y en plein de http ...
ou bien si blount nous sort directement un correctif ça serait plus simple :-P

**Comment by romain1206** [comment]
non pas ceux la

en fait tu prends notepad++ tu fait remplacer http://www.leboncoin.fr par https://www.leboncoin.fr dans toute l'arborescence

**Comment by zebess** [comment]
Quand tu parle d'arborescence, tu veux dire le fichier admin.csv qui référencie toutes les url de mes recherches? 
si oui j'ai déjà fait mais j'ai tjr la mm erreur. J'ai appliqué également ce topic : https://alerte.ilatumi.org/forum/viewtopic.php?id=477
si non, je n'ai pas trouvé d'autres fichiers qui référencie http://www.leboncoin.fr dans leur code.

**Comment by zebess** [comment]
J'ai trouvé la réponse sur le forum ->voici les modifications à effectuer:

J'avais tenté la modification préconisée par Gilles, https://alerte.ilatumi.org/forum/viewto … 1659#p1659, mais manifestement sans aller au bout !
Il y a 3 actions à effectuer :
1- l'ajout de la ligne de code dans le fichier lib/Http/Client/Curl.php : https://alerte.ilatumi.org/forum/viewto … 1665#p1665
2- modifier l'url "http://www.leboncoin.fr" par "https://www.leboncoin.fr" dans tous les scripts .php du site. Il y en a 4 :
- app/admin/scripts/proxy.php
- app/mail/scripts/check.php
- bootstrap.php
- lib/AdService/SiteConfig/Lbc.php
3- modifier toutes les "url de recherche" dans l'interface graphique pour qu'elles commencent par "https"

Si ça peut servir à d'autre.... j'espere que blount va intégrer ces modifications lors de la prochaine maj.

**Comment by Blount** [comment]
Normalement, résolu dans la version 3.2
