### ISSUE TITLE
Array to string conversion sur /app/models/Storage/File/Alert.php

### ISSUE THREAD

**Issue by bplace** [Blount/LBCAlerte#46]
Après avoir fait la MAJ récemment, j'ai eu 3 fois en 24H une même notice :

```
[01-Jun-2016 20:53:33 Europe/Paris] PHP Notice:  Array to string conversion in /home/xxxx/app/models/Storage/File/Alert.php on line 121
```

C'est peut-être un problème réseau, j'utilise TOR, et la notice n'a pop que 3 fois.

Merci pour votre travail.

**Comment by Blount** [comment]
Bonjour,
Avez-vous toujours ce souci ?

**Comment by bplace** [comment]
Bonjour, oui ça arrive régulièrement.

**Comment by Blount** [comment]
Normalement, le bug doit être résolu dans la dernière version 3.4.
Peux-tu essayer ?

Mais il y a le même bug au moment de la suppression d'une alerte qui sera résolu dans la prochaine version.

**Comment by bplace** [comment]
L'erreur n'est pas ressortie depuis un moment, je surveillerai les mails de Watchdog dans les jours qui viennent

**Comment by Blount** [comment]
Ok, je clos le ticket.
N'hésites pas revenir si besoin ;)

**Comment by bplace** [comment]
Hop je l'ai eu hier 
[06-Jun-2017 17:06:46 Europe/Paris] PHP Notice:  Array to string conversion in /home/xxxx/app/models/Storage/File/Alert.php on line 149

**Comment by Blount** [comment]
Oui, celui-ci est corrigé dans la version en cours de développement.
C'est donc normal que tu aies encore cette erreur.
