### ISSUE TITLE
Caractères spéciaux

### ISSUE THREAD

**Issue by arno-github** [Blount/LBCAlerte#47]
Je viens de mettre à jour lbcalert sur mon serveur (3.1 -> 3.2), et il y a un problème avec les flux.
Voici la page en question :
https://framabin.org/?2d13bbcf3fffec29#FxSoECljFE5fofc31FIJ4Ob+GQmg6qU+qkJwF/L1D30=
Et voici ce que me dit Leed à son propos :
This XML document is invalid, likely due to invalid characters. XML error: Invalid document end at line 2, column 1.

Edit: Je ne sais pas si le problème vient d'lbcalert ou de leed, en fait, que j'ai également mis à jour en même temps, car en voulant repartir sur la 3.1, le problème persiste en utilisant toujours la même version de Leed (1.6.1).

**Comment by Blount** [comment]
Bonjour,
Je prépare une nouvelle version qui devrait corriger un souci sur l'encodage de caractères.
Je n'ai pas de date de sortie par contre.

**Comment by arno-github** [comment]
Le 24/10/2016 à 14:17, Blount a écrit :> Bonjour, Je prépare une
nouvelle version qui devrait corriger un > souci sur l'encodage de
caractères. Je n'ai pas de date de sortie par > contre.

Bonjour et merci pour cette réponse, réconfortante :-)

Bonne journée
-- 
Arnaud Calvo

**Comment by Blount** [comment]
Bonjour,
La version 3.3 est en ligne.
Peux-tu la tester et me faire un retour ? (penser à faire un backup)

**Comment by arno-github** [comment]
J'ai installé la nouvelle version, et enfin trouvé comment outre-passer l'identification (via le forum), car LBCAlerte est en https chez moi, et je ne passe donc pas le login et le mot de passe dans l'URL !
Tout semble fonctionner correctement, merci ! (en tout cas le flux s'affiche dans mon lecteur)

**Comment by Blount** [comment]
Il faudrait que je fasse un système de flux via une clé.
J'ai une idée à ce sujet, je vais voir pour la mettre en place.
