### ISSUE TITLE
utiliser un switch pour desactiver une alerte

### ISSUE THREAD

**Issue by nagoli** [Blount/LBCAlerte#49]
bonjour, 
tout d'abord super produit merci ! 
par contre il est pas evident de comprendre que les feu vert sont des switch 
donc on met un prix ou n mail bidon pour desactiver une alerte que l'on veut garder sous le coude. Ce qui n'est pas ideal
voici un exemple de switch basique : http://www.w3schools.com/howto/howto_css_switch.asp
bonne continuation

**Comment by thierrymtp34** [comment]
bonne idée
