### ISSUE TITLE
Config corrompue, message "Un problème est survenu lors de la génération de la page."

### ISSUE THREAD

**Issue by bplace** [Blount/LBCAlerte#53]
Je ne sais pas trop pourquoi, mais un problème de droit d'écriture est apparu, et la config est devenue corrompue.

php_errors.log :

`[15-Jan-2017 18:41:14 Europe/Paris] PHP Warning:  fopen(/home/lbcalert/var/log/info.log): failed to open stream: Permission denied in /home/lbcalert/lib/Log4php/appenders/LoggerAppenderFile.php on line 99`
`[15-Jan-2017 18:41:14 Europe/Paris] PHP Warning:  log4php: [LoggerAppenderRollingFile:default]: Failed opening target file. Closing appender. in /home/lbcalert/lib/Log4php/LoggerAppender.php on line 283`

Dans error.log de l'appli : 

`2017-01-16T13:38:19+01:00 ERROR Config_Lite_Exception_UnexpectedValue : #0 key not found, no default value given. (/home/lbcalert/lib/Config/Lite.php:364)
`
Le fichier config.ini ne contenait plus que [general] et baseurl à l'intérieur. 

Message d'erreur en affichant l'url de l'appli, il m'a suffit de supprimer le fichier config.ini et de refaire la setup pour que accéder à nouveau à l'appli.

**Comment by Blount** [comment]
Merci pour le retour.
Aucune information ne me permet de trouver une éventuelle cause dans le code, je ferme donc le ticket.
Si cela se reproduit et que tu as un scénario à me donner pour reproduire l'erreur, n'hésites pas.

**Comment by hamelg** [comment]
Ce problème m'arrive régulièrement.
A chaque fois, je suis obligé de restaurer un copie de sauvegarde.
ce sera pas un problème d'accès concurrent ?

Exemple de fichier corrompu :

[general]
baseurl = "http://xxxxxx.lan/www/lbcalerte/"
l = "http://xxxxxx.lan/www/lbcalerte/"

[storage]
type = "db"
options[host] = "localhost"
options[user] = "xxx"
options[password] = "xxx"
options[dbname] = "xxx"

[mailer]
smtp[host] = ""
smtp[port] = ""
smtp[username] = ""
smtp[password] = ""
smtp[secure] = ""
smtp[allow_self_signed] = ""
from = "xxxxx@zzzz.net"
