### ISSUE TITLE
Option to disable the URL shortener (in SMS notifications)

### ISSUE THREAD

**Issue by C-Duv** [Blount/LBCAlerte#54]
I don't see any advantage of using an URL shortener in SMS notifications: would you add an config parameter to disable it?

**Comment by Blount** [comment]
The length of SMSs is limited. The title of alert and of the ad are used to build the message. Also, I need to minimize the size of URL : 
http://tinyurl.com/gna8kuc
is lot shorter than
https://www.leboncoin.fr/chaussures/890380423.htm?ca=8_s

**Comment by C-Duv** [comment]
I understand, looks like I ran into the issue described in the forum [where TinyURL URLs were redirecting to empty pages at beta.leboncoin.fr](https://alerte.ilatumi.org/forum/viewtopic.php?id=505).

That being said, I disabled shortener on my instance and never had issue with SMS length (yet), using Free Mobile SMS service.

**Comment by cpecquerie** [comment]
One of the issue of forcing tinyurl is that it disables URL schemes on iOS or Android : instead of opening the leboncoin app directly, it will open the browser since the OS detects the tinyurl scheme.
I've also disabled TinyURL in my instance manually but an option would be awesome.

**Comment by Blount** [comment]
I work to disable URL shortener.
Two different URL are used : ad url and search URL.
The ad url is used when I send a SMS for single ad. The search URL (use to create the alert) is used when more than five ads are found to avoid SMS cost.

Also, search URL can overflow the SMS limitation.

I suggest to remove the URL shortener for ads and conserve it for search URL.
What do you think ?

**Comment by cpecquerie** [comment]
Yes it sounds like a great compromise. 
		
		

		Obtenez Outlook pour iOS
	




On Sun, Jul 23, 2017 at 6:33 PM +0200, "Blount" <notifications@github.com> wrote:












I work to disable URL shortener.

Two different URL are used : ad url and search URL.

The ad url is used when I send a SMS for single ad. The search URL (use to create the alert) is used when more than five ads are found to avoid SMS cost.


Also, search URL can overflow the SMS limitation.


I suggest to remove the URL shortener for ads and conserve it for search URL.

What do you think ?

**Comment by Blount** [comment]
Fixed in 3.6.1. Please, upgrade Cheky to 3.6.1 (after backup ^^).
