### ISSUE TITLE
Privacy of LBCAlerte instance: set "Referrer Policy" to "same-origin"

### ISSUE THREAD

**Issue by C-Duv** [Blount/LBCAlerte#55]
Links to leboncoin.fr/seloger.com websites from the _LBCAlerte_ interface can reveal the _LBCAlerte_ instance's URL via the *referrer*. Which they could use to find the instance's IP and eventually block it.

I suggest to take measures to protect our instances from this "possible" lockdown.
One simple option that works on modern browsers, it to prevent the `Referer` HTTP header to be added to the HTTP request.

It is done be setting the [referrer-policy](https://www.w3.org/TR/referrer-policy/) to [`same-origin`](https://www.w3.org/TR/referrer-policy/#referrer-policy-same-origin) via any of the following method:
* the [`Referrer-Policy` HTTP header](https://www.w3.org/TR/referrer-policy/#referrer-policy-header)
* a [`<meta> element`](https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery-meta)
* or the [`rel="noreferrer"` on `<a>` elements](https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery-referrer-attribute) that points to theses websites.

**Comment by Blount** [comment]
You right.
I know that the referer is not transmitted from https protocol to http protocol. But, it might be sended from https to https.

**Comment by C-Duv** [comment]
Great, I'll file a PR for that :)
