### ISSUE TITLE
ajouter les coordonner mail/telephone lors de la sauvegarde d'une annonce.

### ISSUE THREAD

**Issue by jzahraoui** [Blount/LBCAlerte#57]
bonjour,

je pense que tout est dans le titre :
"ajouter les coordonner mail/telephone lors de la sauvegarde d'une annonce."
effectivement c'est une donnée très importante qui est manquante.
je ne sais pas si techniquement c'est difficile à faire et que c'est pour ca qu'il ne le fait pas.
merci bien.

**Comment by Blount** [comment]
Bonjour.
Pour le mail, impossible. Leboncoin ne fourni pas cette information, il faut passer par leur formulaire pour contacter le vendeur.

Pour le téléphone, comme il n'est pas dans les infos fournies dans la liste de résultat, cela nécessiterait au moins 2 requêtes supplémentaires pour le récupérer ce qui est trop lourd.

**Comment by jzahraoui** [comment]
merci pour votre réponse rapide.
