### ISSUE TITLE
slack webhooks Protocol http not supported or disabled in libcurl 

### ISSUE THREAD

**Issue by HugoGresse** [Blount/LBCAlerte#58]
J'ai l'erreur suivante en testant une webhook sur slack en http ou https: 

> Le test d'envoi a échoué :
> Erreur lors de l'envoi de la notification : (0) cURL Error: Protocol http not supported or disabled in libcurl 

install clean qui date d'aujourd'hui en utilisant le système de fichier (pas MySQL)

**Comment by Blount** [comment]
Hmmm, le message indique que cURL installé sur votre système ne vous permet pas d'utiliser le protocole http. Je ne connais pas du tout slack et ne saurais donc pas en dire plus.

**Comment by HugoGresse** [comment]
je suis d'accord pour la stack sauf que je suis en mutualisé OVH où PHP est installé avec cURL. 

phpinfo : http://hugo.gresse.io/lbc/info.php

**Comment by Blount** [comment]
Dans ce cas, essaie en ligne de commande un truc de ce genre : 
wget https://www.leboncoin.fr
pour voir si ca passe.
