### ISSUE TITLE
[Question] Diff avec le système d'alerte intégré dans LBC

### ISSUE THREAD

**Issue by HugoGresse** [Blount/LBCAlerte#59]
Bonjour,

J'ai du mal à comprendre la différence avec le système d'alerte intégré aux comptes sur le bon coin. Celui si marche aussi pour se loger mais sinon ?

**Comment by Blount** [comment]
Les alertes fournis par Leboncoin ne peuvent se faire que sur la catégorie "Immobilier". Il n'est pas possible d'avoir la main sur l'intervalle de temps entre 2 alertes. En outre, une annonce postée à l'instant, vous pourriez n'en recevoir l'alerte que demain.
LBCAlerte permet aussi quelques filtres supplémentaires (ex: filtre prix sur tranche libre et sur n'importe quelle catégorie).
Avec LBCAlerte, les alertes ne se contentent pas d'être envoyées par email, vous pouvez recevoir par SMS, sur mobile via des applications (ex: Pushbullet) ou encore via des flux RSS.

Mais effectivement, si les alertes de Leboncoin vous suffisent, LBCAlerte ne vous sera pas indispensable.

**Comment by HugoGresse** [comment]
merci pour la réponse, je garde quand même LBC Alerte
