### ISSUE TITLE
Erreur fichier .lock

### ISSUE THREAD

**Issue by xguitoux** [Blount/LBCAlerte#60]
Bonjour,

tout d'abord un grand merci pour ton appli c'est vraiment super pratique.

Par contre je rencontre le bug du fichier .lock (Processus en cours d'utilisation), du coup supprimer à chaque fois le fichier à la main ça devient pénible (tous les jours environ)

Côté environnement je suis sur un NAS Synology, 4 alertes dont une sur SeLoger avec pas mal de résultats remontés.
Cron + alertes toutes les 30 min
Hébergement fichiers (j'ai pas retrouvé mon mdp sql à l'installation ^^)

Je me pose la question si ça ne serait pas la 'grosse' requête Seloger qui foutrait la merde.

Je vais essayer de la "découper" en plusieurs en attendant d'avoir ton avis sur la question.

Merci encore

**Comment by Blount** [comment]
Salut.
Oui, en effet, il semble y avoir un souci avec SeLoger qui génère un fatal error.
Avec PHP7, l'erreur est traitée correctement car les fatal error peuvent être "attrapées".

**Comment by xguitoux** [comment]
Si tu as déjà identifié la méthode qui plante avec SeLoger, un petit try/catch autour ne ferait pas l'affaire ?

**Comment by xguitoux** [comment]
Bon ben en attendant j'ai fait un script de suppression du fichier lock qui tourne via cron toutes les 30 min.

**Comment by Blount** [comment]
L'erreur est corrigée dans la version 3.4, je t'invite donc à mettre à jour ta version.
