### ISSUE TITLE
check.php error loading modules

### ISSUE THREAD

**Issue by Draky50110** [Blount/LBCAlerte#62]
Hello.

Runing check.php gives error : 

PHP Warning:  Module 'xsl' already loaded in Unknown on line 0
PHP Warning:  Module 'zip' already loaded in Unknown on line 0

Those modules are already loaded by default on my webhost...

**Comment by Blount** [comment]
I can't reproduce this error.
Can you execute this command : 
php -r 'echo "Hello world\n";'

Have you the same error ?

**Comment by Draky50110** [comment]
For history : loaded module in webhost environment was the problem and PHP command could not execute.
