### ISSUE TITLE
Notice PHP ps_files_cleanup_dir

### ISSUE THREAD

**Issue by bplace** [Blount/LBCAlerte#68]
Hello, petite notice qui pop très rarement:

[27-Jun-2017 19:52:56 Europe/Paris] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5) failed: Permission denied (13) in /home/lbcalert/lib/Auth/Session.php on line 12

**Comment by tomlaredo** [comment]
Bonjour,

Il s'agit d'un problème de configuration de votre serveur (droits UNIX incorrects).
Le script /home/lbcalert/lib/Auth/Session.php tente d'ouvrir /var/lib/php5 et le système refuse.
La commande pour solutionner ce problème dépend de la distribution de votre serveur (Debian, RedHat...).

**Comment by Blount** [comment]
Bonjour,
Je pense qu'il ne s'agit pas d'un problème lié à Cheky.
Une piste : 
https://stackoverflow.com/questions/2904862/issues-with-php-5-3-and-sessions-folder
