### ISSUE TITLE
Erreur de connexion

### ISSUE THREAD

**Issue by bambix** [Blount/LBCAlerte#70]
Bonjour,

Je reçois de facon périodique un email contenant : 
Un problème est survenu lors de l'exécution du programme.

En cherchant un peut cela correspond a la ligne suivant dans les logs :
2017-08-07T16:27:06+02:00 ERROR Exception : #0 Connexion vers https://www.leboncoin.fr échouée (erreur: Operation timed out after 0 milliseconds with 0 out of 0 bytes received). (/var/www/leboncoin/LBCAlerte/app/notifier/scripts/check.php:513)

Je passe par un proxy connecté au réseau TOR pour attaquer LBC.

J'ai l'impression que cela correspond à un blacklistage de l'IP TOR depuis LBC, pourriez-vous m'en dire plus ?

Merci d'avance

**Comment by Blount** [comment]
Je vois deux possibilités : 
- blacklisté : impossible donc de se connecter sur Leboncoin.
- coupure réseau : il peut y avoir des coupures réseaux du serveur où est hébergé Cheky. Une surcharge serveur peut aussi provoquer cette erreur.
