### ISSUE TITLE
Test mail 

### ISSUE THREAD

**Issue by Neeko09** [Blount/LBCAlerte#72]
Salut Blount, 
Déjà un grand merci pour cette application.
En ce qui concerne l'utilisation avec un serveur gmail aucun soucis les alertes sont bien envoyées, néanmoins pour le test de la boite mail, celle-ci me renvoi sur :

"Cette page ne fonctionne pas

Impossible de traiter cette demande via **********.org à l'heure actuelle.
HTTP ERROR 500"
 en ce qui concerne /var/www/*****/log/info.log   R.A.S il ne détecte aucun bug.

Bonne journée à toi et merci encore.

**Comment by Blount** [comment]
Corrigé dans la version 3.6.1

**Comment by jief666** [comment]
Bonjour,
comment faire un test d'envoi d'email ?
Merci.
