### ISSUE TITLE
Pouvoir modifier les valeurs check_start et check_end

### ISSUE THREAD

**Issue by AntoineTurmel** [Blount/LBCAlerte#77]
Pouvoir modifier les valeurs check_start et check_end dans l'interface d'administration

**Comment by Blount** [comment]
Bonjour,
Quel serait l'intérêt de l'avoir dans l'admin ? Étant donné que ces valeurs subissent très peu de modification, ce n'est pas vraiment pénalisant d'aller dans le fichier config pour le faire ?

**Comment by AntoineTurmel** [comment]
Bah en installant, j'avais l'impression que ça ne fonctionnait pas, et après moultes recherche sj'ai découvert qu'il y avait ces valeurs qui faisait que ça ne checkais pas ^^'
Si je crois bien ce n'est indiqué nulle part que la recherche se fait sur un créneau horaire.

**Comment by Blount** [comment]
Ah ok, je comprend mieux ^^
Normalement, dans les logs il doit y avoir un truc de marqué "Hors de la plage horaire. Contrôle annulé".
Après, un petit mot dans la doc ne serait pas de trop.
D'ailleurs, ce serait sous forme de FAQ je pense.
Je ferme du coup car je ne pense pas mettre ca dans l'admin un jour ^^

**Comment by AntoineTurmel** [comment]
Ah ok, dommage je trouve ça pratique d'avoir des alertes H24... j'avais bien vu le message dans les logs justement, mais je me demandais où étais ce réglage de plage horaire ^^
