### ISSUE TITLE
"Un problème est survenu lors de l'exécution du programme." check.php

### ISSUE THREAD

**Issue by metasystem** [Blount/LBCAlerte#79]
Bonjour,
Je viens d'installer LBCAlerte sur apache2/php7.0 sur archlinux.
en root ou en utilisateur http, le script n'est pas fonctionnel.
J'ai pas vu de debbug dans les commandes php, du coup, je viens vers vous.

**Comment by Blount** [comment]
Il y a un fichier log dans le répertoire var/log ou aussi accessible dans le panneau d'admin onglet log.
Tu devrai avoir des infos.

**Comment by metasystem** [comment]
"2017-08-28T14:15:02+02:00 ERROR Error : #0 Call to undefined function iconv() (/srv/http/lib/Http/Client/Curl.php:62) "
J'ai été vérifier, curl est est bien installé et "extension=curl.so" n'est pas commenté dans le php.ini.

**Comment by Blount** [comment]
Ce n'est pas cURL c'est "iconv". Tu as peut-être un extension=iconv.so de commenté ?

**Comment by metasystem** [comment]
Problème résolut, mais toutefois.

"2017-08-28T14:25:17+02:00 WARN [Pid 9429] USER : admin - ALERT ID : 8919f86f338594619d9ef1c8c56d413b2433970b -> Impossible d'instancier la fonction mail."

pareil pour toutes les alertes

**Comment by Blount** [comment]
La fonction mail() est bien active sur ta config PHP ?
Sinon, tu peux utiliser un serveur SMTP (voir admin).

**Comment by metasystem** [comment]
merci, impec avec le smtp
