### ISSUE TITLE
En-tête d'e-mail "X-Mailer" dédiée

### ISSUE THREAD

**Issue by C-Duv** [Blount/LBCAlerte#80]
Je trouverais pratique que les e-mails émis par Cheky aient une en-tête dédiée, ça permet de simplifier ses filtres/règles de classement d'e-mail sur son client de messagerie.

Actuellement, les e-mails émis par Cheky ont l'en-tête suivante :
`X-Mailer: PHPMailer 5.2.7 (https://github.com/PHPMailer/PHPMailer/)`

Je propose quelque chose comme :
`X-Mailer: Cheky`

Il peut être intéressant d'avoir la version, on peut aussi ajouter l'en-tête `X-Mailer-Version` telle qu'on aurait alors :
```
X-Mailer: Cheky
X-Mailer-Version: 3.6.1
```
(La version permet notamment de débuguer plus facilement lors qu'un problème est signalé sur un e-mail)

La librairie utilisée (PHPMailer) le permet ainsi :
```PHP
$mail->addCustomHeader('X-Mailer', 'Cheky');
$mail->addCustomHeader('X-Mailer-Version ', APPLICATION_VERSION);
```

A rajouter vers les lignes 55-57 de `/app/notifier/scripts/check.php`  par exemple : https://github.com/Blount/LBCAlerte/blob/22e26b5d467825e03f9d02fd94aac5a92490a230/app/notifier/scripts/check.php#L55-L57

**Comment by C-Duv** [comment]
Généralement, `X-Mailer` est assez libre.
Tu as raison pour les catégorie : c'est typiquement ce que fait Redmine.
GitHub utilise aussi des en-tête dédiée.

* `X-Mailer: Redmine`
* `X-Redmine-Project; Foobar`
* `X-Redmine-Issue-Id: 42`
* `X-GitHub-Reason: mention`

**Comment by C-Duv** [comment]
Au fait, je n'avais pas pris le temps de te remercier d'avoir intégré ma proposition : Merci :+1:

**Comment by Blount** [comment]
De rien ;)
